### ISSUE TITLE
FR Translations needed

### ISSUE THREAD

**Issue by velrest** [inosca/ember-ebau-gwr#598]
```yaml
forbiddenBuildingClassError: "Die Gebäudeklasse "Landwirtschaftliche Betriebsgebäude" darf bei der Erfassung von Gebäuden (Neubau) nicht mehr vergeben werden. Wählen Sie anstelle aus den folgenden Gebäudeklassen: "Gebäude für die Tierhaltung", "Gebäude für den Pflanzenbau" und "Andere landwirtschaftliche Gebäude"."
linkedWithBuilding: Verknüpft mit Gebäude
typeOfConstructionProject: Art der Bauwerke
typeOfConstructionProjectPlaceholder: Wählen Sie einen Art der Bauwerke...
specialstructureInfo: Für Sonderbauprojekte sind ausschliesslich Gebäude der Gebäudekategorie Sonderbau zugelassen.
```
